# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2201182e140e53a89fde0ab19901b9d4044484faf3f3c0a89e50d51e6517c4078ec82590ffa03e65e4958650f937ff6390c7bb9ed81d3674c2e7f85856a0fe3

test:
  secret_key_base: 2cf0353415db3c8577439f3b9f0f708d0b64eb3b187dfa4d205f4a729734586d181b2db282f071a234977dd0ba13d6849a995c2198c51ab80105f2b565625882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
